[package]
name = "slugid"
version = "1.0.0"
authors = ["Wander Lairson Costa <wander.lairson@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["v4"] }
base64 = { version = "0.12.3" }
